"""LogForge Processed Log Event Database Model.

Preserves exact raw event, normalized event representation, unmapped vendor
fields, and cryptographic SHA-256 hash without loss or mutation.
"""
from datetime import datetime, timezone
from typing import Any, Dict, Optional

from sqlalchemy import BigInteger, DateTime, Index, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import JSON

from ..db.base import Base

# Dialect-agnostic JSON type: Native JSONB in PostgreSQL, standard JSON in SQLite
JsonType = JSON().with_variant(JSONB, "postgresql")


class EventModel(Base):
    """Processed security log event record."""

    __tablename__ = "events"

    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )

    # Event ID generated by the ULPF Engine (UUIDv4)
    event_id: Mapped[str] = mapped_column(
        String(36), unique=True, index=True, nullable=False, doc="Unique UUIDv4 assigned by ULPF engine"
    )

    # Extracted event timestamp
    timestamp: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), index=True, nullable=True, doc="Normalized event occurrence timestamp"
    )

    # Format classification: 'json', 'cef', 'syslog', etc.
    detected_format: Mapped[str] = mapped_column(
        String(32), index=True, nullable=False, doc="Deterministic format detected by ULPF"
    )

    # Canonical network and security entities
    source_ip: Mapped[Optional[str]] = mapped_column(String(64), index=True, nullable=True)
    destination_ip: Mapped[Optional[str]] = mapped_column(String(64), index=True, nullable=True)
    source_port: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    destination_port: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    protocol: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    action: Mapped[Optional[str]] = mapped_column(String(64), index=True, nullable=True)
    severity: Mapped[Optional[str]] = mapped_column(String(32), index=True, nullable=True)

    # EXACT byte-for-byte raw event as received (Zero trimming, zero mutation, 100% lossless)
    raw_event: Mapped[str] = mapped_column(
        Text, nullable=False, doc="Pristine exact raw log line without any modification"
    )

    # Universal Event Schema normalized dictionary
    normalized_event: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JsonType, nullable=True, doc="Universal Event Schema (UES) JSON representation"
    )

    # Unmapped vendor fields preserving any extension/attribute losslessly
    additional_fields: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JsonType, nullable=True, doc="Extensible dictionary of unmapped vendor attributes"
    )

    # Cryptographic SHA-256 hash computed by ULPF engine over raw_event
    sha256_hash: Mapped[str] = mapped_column(
        String(64), nullable=False, doc="Cryptographic SHA-256 digest of pristine raw_event"
    )

    # Record insertion timestamp
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=lambda: datetime.now(timezone.utc),
        doc="Database persistence timestamp",
    )

    # Composite index for time-range + severity queries
    __table_args__ = (
        Index("ix_events_created_at", "created_at"),
        Index("ix_events_timestamp_severity", "timestamp", "severity"),
    )

    def __repr__(self) -> str:
        return f"<EventModel(id={self.id}, event_id='{self.event_id}', format='{self.detected_format}', action='{self.action}')>"
